apiVersion: v1
kind: Pod
metadata:
  name: gianninoderedis
spec:
  containers:
    - name: gianninoderedis
      image: cloud.canister.io:5000/arhturescriou/node-redis
      imagePullPolicy: IfNotPresent
      env:
        - name: PORT
          value: "6379"
        - name: REDIS_URL
          value: "redis://10.2.4.4"
